// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/v1/example.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfrastructureExecution struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId      string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	InfrastructureId string                 `protobuf:"bytes,2,opt,name=infrastructure_id,json=infrastructureId,proto3" json:"infrastructure_id,omitempty"`
	StartedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	StoppedAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	InstanceIds      []string               `protobuf:"bytes,5,rep,name=instance_ids,json=instanceIds,proto3" json:"instance_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InfrastructureExecution) Reset() {
	*x = InfrastructureExecution{}
	mi := &file_proto_v1_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfrastructureExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfrastructureExecution) ProtoMessage() {}

func (x *InfrastructureExecution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfrastructureExecution.ProtoReflect.Descriptor instead.
func (*InfrastructureExecution) Descriptor() ([]byte, []int) {
	return file_proto_v1_example_proto_rawDescGZIP(), []int{0}
}

func (x *InfrastructureExecution) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *InfrastructureExecution) GetInfrastructureId() string {
	if x != nil {
		return x.InfrastructureId
	}
	return ""
}

func (x *InfrastructureExecution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *InfrastructureExecution) GetStoppedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StoppedAt
	}
	return nil
}

func (x *InfrastructureExecution) GetInstanceIds() []string {
	if x != nil {
		return x.InstanceIds
	}
	return nil
}

var File_proto_v1_example_proto protoreflect.FileDescriptor

const file_proto_v1_example_proto_rawDesc = "" +
	"\n" +
	"\x16proto/v1/example.proto\x12\n" +
	"example.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x02\n" +
	"\x17InfrastructureExecution\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12+\n" +
	"\x11infrastructure_id\x18\x02 \x01(\tR\x10infrastructureId\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\n" +
	"stopped_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstoppedAt\x12!\n" +
	"\finstance_ids\x18\x05 \x03(\tR\vinstanceIdsB0Z.github.com/example/protobuf-compat/proto/v1;v1b\x06proto3"

var (
	file_proto_v1_example_proto_rawDescOnce sync.Once
	file_proto_v1_example_proto_rawDescData []byte
)

func file_proto_v1_example_proto_rawDescGZIP() []byte {
	file_proto_v1_example_proto_rawDescOnce.Do(func() {
		file_proto_v1_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_example_proto_rawDesc), len(file_proto_v1_example_proto_rawDesc)))
	})
	return file_proto_v1_example_proto_rawDescData
}

var file_proto_v1_example_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_example_proto_goTypes = []any{
	(*InfrastructureExecution)(nil), // 0: example.v1.InfrastructureExecution
	(*timestamppb.Timestamp)(nil),   // 1: google.protobuf.Timestamp
}
var file_proto_v1_example_proto_depIdxs = []int32{
	1, // 0: example.v1.InfrastructureExecution.started_at:type_name -> google.protobuf.Timestamp
	1, // 1: example.v1.InfrastructureExecution.stopped_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_example_proto_init() }
func file_proto_v1_example_proto_init() {
	if File_proto_v1_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_example_proto_rawDesc), len(file_proto_v1_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_example_proto_goTypes,
		DependencyIndexes: file_proto_v1_example_proto_depIdxs,
		MessageInfos:      file_proto_v1_example_proto_msgTypes,
	}.Build()
	File_proto_v1_example_proto = out.File
	file_proto_v1_example_proto_goTypes = nil
	file_proto_v1_example_proto_depIdxs = nil
}
